// Code generated by scripts/gen_damagetypes.py from misode/mcmeta 1.21.5. DO NOT EDIT.

package protocol

// damageType holds the network fields of one minecraft:damage_type entry.
type damageType struct {
	Name             string
	MessageID        string
	Scaling          string
	Exhaustion       float32
	Effects          string
	DeathMessageType string
}

var damageTypes = []damageType{
	{"arrow", "arrow", "when_caused_by_living_non_player", 0.1, "", ""},
	{"bad_respawn_point", "badRespawnPoint", "always", 0.1, "", "intentional_game_design"},
	{"cactus", "cactus", "when_caused_by_living_non_player", 0.1, "", ""},
	{"campfire", "inFire", "when_caused_by_living_non_player", 0.1, "burning", ""},
	{"cramming", "cramming", "when_caused_by_living_non_player", 0, "", ""},
	{"dragon_breath", "dragonBreath", "when_caused_by_living_non_player", 0, "", ""},
	{"drown", "drown", "when_caused_by_living_non_player", 0, "drowning", ""},
	{"dry_out", "dryout", "when_caused_by_living_non_player", 0.1, "", ""},
	{"ender_pearl", "fall", "when_caused_by_living_non_player", 0, "", "fall_variants"},
	{"explosion", "explosion", "always", 0.1, "", ""},
	{"fall", "fall", "when_caused_by_living_non_player", 0, "", "fall_variants"},
	{"falling_anvil", "anvil", "when_caused_by_living_non_player", 0.1, "", ""},
	{"falling_block", "fallingBlock", "when_caused_by_living_non_player", 0.1, "", ""},
	{"falling_stalactite", "fallingStalactite", "when_caused_by_living_non_player", 0.1, "", ""},
	{"fireball", "fireball", "when_caused_by_living_non_player", 0.1, "burning", ""},
	{"fireworks", "fireworks", "when_caused_by_living_non_player", 0.1, "", ""},
	{"fly_into_wall", "flyIntoWall", "when_caused_by_living_non_player", 0, "", ""},
	{"freeze", "freeze", "when_caused_by_living_non_player", 0, "freezing", ""},
	{"generic", "generic", "when_caused_by_living_non_player", 0, "", ""},
	{"generic_kill", "genericKill", "when_caused_by_living_non_player", 0, "", ""},
	{"hot_floor", "hotFloor", "when_caused_by_living_non_player", 0.1, "burning", ""},
	{"in_fire", "inFire", "when_caused_by_living_non_player", 0.1, "burning", ""},
	{"in_wall", "inWall", "when_caused_by_living_non_player", 0, "", ""},
	{"indirect_magic", "indirectMagic", "when_caused_by_living_non_player", 0, "", ""},
	{"lava", "lava", "when_caused_by_living_non_player", 0.1, "burning", ""},
	{"lightning_bolt", "lightningBolt", "when_caused_by_living_non_player", 0.1, "", ""},
	{"mace_smash", "mace_smash", "when_caused_by_living_non_player", 0.1, "", ""},
	{"magic", "magic", "when_caused_by_living_non_player", 0, "", ""},
	{"mob_attack", "mob", "when_caused_by_living_non_player", 0.1, "", ""},
	{"mob_attack_no_aggro", "mob", "when_caused_by_living_non_player", 0.1, "", ""},
	{"mob_projectile", "mob", "when_caused_by_living_non_player", 0.1, "", ""},
	{"on_fire", "onFire", "when_caused_by_living_non_player", 0, "burning", ""},
	{"out_of_world", "outOfWorld", "when_caused_by_living_non_player", 0, "", ""},
	{"outside_border", "outsideBorder", "when_caused_by_living_non_player", 0, "", ""},
	{"player_attack", "player", "when_caused_by_living_non_player", 0.1, "", ""},
	{"player_explosion", "explosion.player", "always", 0.1, "", ""},
	{"sonic_boom", "sonic_boom", "always", 0, "", ""},
	{"spit", "mob", "when_caused_by_living_non_player", 0.1, "", ""},
	{"stalagmite", "stalagmite", "when_caused_by_living_non_player", 0, "", ""},
	{"starve", "starve", "when_caused_by_living_non_player", 0, "", ""},
	{"sting", "sting", "when_caused_by_living_non_player", 0.1, "", ""},
	{"sweet_berry_bush", "sweetBerryBush", "when_caused_by_living_non_player", 0.1, "poking", ""},
	{"thorns", "thorns", "when_caused_by_living_non_player", 0.1, "thorns", ""},
	{"thrown", "thrown", "when_caused_by_living_non_player", 0.1, "", ""},
	{"trident", "trident", "when_caused_by_living_non_player", 0.1, "", ""},
	{"unattributed_fireball", "onFire", "when_caused_by_living_non_player", 0.1, "burning", ""},
	{"wind_charge", "mob", "when_caused_by_living_non_player", 0.1, "", ""},
	{"wither", "wither", "when_caused_by_living_non_player", 0, "", ""},
	{"wither_skull", "witherSkull", "when_caused_by_living_non_player", 0.1, "", ""},
}
