// Code generated by tachyne-world/scripts/gen_smithingdata.py; DO NOT EDIT.

package protocol

// SmithingUpgradeTemplate is the netherite upgrade template item.
const SmithingUpgradeTemplate = 1579

// SmithingTransform maps a transform base item to its upgraded result.
var SmithingTransform = map[int32]int32{
	1050: 1055,
	1051: 1056,
	1052: 1057,
	1053: 1058,
	1054: 1059,
	1084: 1092,
	1085: 1093,
	1086: 1094,
	1087: 1095,
	1409: 1410,
	1452: 1453,
	1487: 1488,
}

// SmithingTrimTemplate maps a trim template item to its trim_pattern id
// (OUR declared alphabetical registry order, identical on every version).
var SmithingTrimTemplate = map[int32]int32{
	1580: 8,
	1581: 2,
	1582: 1,
	1583: 17,
	1584: 15,
	1585: 3,
	1586: 14,
	1587: 13,
	1588: 11,
	1589: 7,
	1590: 12,
	1591: 16,
	1592: 9,
	1593: 10,
	1594: 6,
	1595: 5,
	1596: 4,
	1597: 0,
}

// SmithingTrimMaterial maps an addition item to its trim_material id.
var SmithingTrimMaterial = map[int32]int32{
	1016: 0,
	1020: 1,
	1012: 2,
	1013: 3,
	1022: 4,
	1018: 5,
	1014: 6,
	1023: 7,
	1015: 8,
	824:  9,
	1397: 10,
}

// SmithingTrimmable lists the trimmable armor items.
var SmithingTrimmable = []int32{1001, 1068, 1069, 1070, 1071, 1072, 1073, 1074, 1075, 1076, 1077, 1078, 1079, 1080, 1081, 1082, 1083, 1084, 1085, 1086, 1087, 1088, 1089, 1090, 1091, 1092, 1093, 1094, 1095}
