// Code generated by tachyne-world/scripts/gen_smithingdata.py; DO NOT EDIT.

package protocol

// SmithingUpgradeTemplate is the netherite upgrade template item.
const SmithingUpgradeTemplate = 1426

// SmithingTransform maps a transform base item to its upgraded result.
var SmithingTransform = map[int32]int32{
	936:  941,
	937:  942,
	938:  943,
	939:  944,
	940:  945,
	970:  978,
	971:  979,
	972:  980,
	973:  981,
	1258: 1259,
	1301: 1302,
	1335: 1336,
}

// SmithingTrimTemplate maps a trim template item to its trim_pattern id
// (OUR declared alphabetical registry order, identical on every version).
var SmithingTrimTemplate = map[int32]int32{
	1427: 8,
	1428: 2,
	1429: 1,
	1430: 17,
	1431: 15,
	1432: 3,
	1433: 14,
	1434: 13,
	1435: 11,
	1436: 7,
	1437: 12,
	1438: 16,
	1439: 9,
	1440: 10,
	1441: 6,
	1442: 5,
	1443: 4,
	1444: 0,
}

// SmithingTrimMaterial maps an addition item to its trim_material id.
var SmithingTrimMaterial = map[int32]int32{
	902:  0,
	906:  1,
	898:  2,
	899:  3,
	908:  4,
	904:  5,
	900:  6,
	909:  7,
	901:  8,
	717:  9,
	1246: 10,
}

// SmithingTrimmable lists the trimmable armor items.
var SmithingTrimmable = []int32{887, 954, 955, 956, 957, 958, 959, 960, 961, 962, 963, 964, 965, 966, 967, 968, 969, 970, 971, 972, 973, 974, 975, 976, 977, 978, 979, 980, 981}
