#!/usr/bin/env python3
"""Generate protocol/recipesets_gen.go: vanilla's recipe property sets.

Usage: gen_recipe_sets.py <server.jar or its inner server jar> [out.go]

RecipeManager builds each RecipePropertySet from the loaded recipes'
ingredients: smithing_template/base/addition from the smithing recipes
(transform and trim), furnace/blast_furnace/smoker/campfire_input from the
cooking recipes of each type, brewing_input/brewing_reagent from the
brewing recipes' input and reagent items. Tags are expanded through the
jar's item tags. Items the canonical item registry lacks (feature-flagged
extras, as asPropertySet's enabled-flags filter drops them) are left out.
Each set is written in canonical item id order.
"""
import json
import os
import re
import sys
import zipfile

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)

SETS = [  # RecipePropertySet's declaration order
    "smithing_base", "smithing_template", "smithing_addition",
    "furnace_input", "blast_furnace_input", "smoker_input", "campfire_input",
    "brewing_input", "brewing_reagent",
]
COOKING = {
    "minecraft:smelting": "furnace_input",
    "minecraft:blasting": "blast_furnace_input",
    "minecraft:smoking": "smoker_input",
    "minecraft:campfire_cooking": "campfire_input",
}


def open_jar(path):
    z = zipfile.ZipFile(path)
    if any(n.startswith("data/minecraft/recipe/") for n in z.namelist()):
        return z
    # the bundler jar: the server jar is inside META-INF/versions
    for n in z.namelist():
        if n.startswith("META-INF/versions/") and n.endswith(".jar"):
            import io
            return zipfile.ZipFile(io.BytesIO(z.read(n)))
    sys.exit("no recipes in " + path)


def canonical_items():
    src = open(os.path.join(ROOT, "protocol", "canonicalnames_gen.go")).read()
    block = src[src.index("var canonicalItemIDs"):]
    block = block[: block.index("\n}\n")]
    return {m.group(1): int(m.group(2)) for m in re.finditer(r'"([^"]+)":\s*(\d+)', block)}


def main():
    z = open_jar(sys.argv[1])
    out = sys.argv[2] if len(sys.argv) > 2 else os.path.join(ROOT, "protocol", "recipesets_gen.go")
    items = canonical_items()
    tags = {}
    for n in z.namelist():
        m = re.match(r"data/minecraft/tags/item/(.+)\.json$", n)
        if m:
            tags["minecraft:" + m.group(1)] = json.loads(z.read(n))["values"]

    def expand(ref, seen=()):
        if isinstance(ref, dict):
            ref = ref["id"]
        if ref.startswith("#"):
            name = ref[1:]
            if name in seen:
                return []
            res = []
            for v in tags.get(name, []):
                res += expand(v, seen + (name,))
            return res
        return [ref]

    def ingredient(v):
        if v is None:
            return []
        if isinstance(v, list):
            res = []
            for e in v:
                res += expand(e)
            return res
        return expand(v)

    sets = {k: set() for k in SETS}
    for n in z.namelist():
        if not (n.startswith("data/minecraft/recipe/") and n.endswith(".json")):
            continue
        r = json.loads(z.read(n))
        t = r["type"]
        if t in ("minecraft:smithing_transform", "minecraft:smithing_trim"):
            sets["smithing_base"].update(ingredient(r.get("base")))
            sets["smithing_template"].update(ingredient(r.get("template")))
            sets["smithing_addition"].update(ingredient(r.get("addition")))
        elif t in COOKING:
            sets[COOKING[t]].update(ingredient(r.get("ingredient")))
        elif t == "minecraft:brewing":
            sets["brewing_input"].update(ingredient(r["input"]["item"]))
            sets["brewing_reagent"].update(ingredient(r["reagent"]["item"]))

    lines = [
        "// Code generated by scripts/gen_recipe_sets.py; DO NOT EDIT.",
        "",
        "package protocol",
        "",
        "// RecipePropertySets are vanilla's recipe property sets (RecipeManager's",
        "// synchronized item properties, as update_recipes carries them): each",
        "// set's key and its items by canonical name, in canonical id order.",
        "var RecipePropertySets = []struct {",
        "\tKey   string",
        "\tItems []string",
        "}{",
    ]
    for k in SETS:
        names = sorted({i[len("minecraft:"):] for i in sets[k] if i[len("minecraft:"):] in items},
                       key=lambda s: items[s])
        if not names:
            sys.exit("empty set " + k)
        lines.append('\t{"minecraft:%s", []string{%s}},' % (k, ", ".join('"%s"' % s for s in names)))
    lines.append("}")
    open(out, "w").write("\n".join(lines) + "\n")


main()
